### ISSUE TITLE
关于Top 10 Python libraries of 2016的翻译

### ISSUE THREAD

**Issue by ictar** [PyCN/PTR#14]
划分如下，小伙伴们自行认领
* 开头 - Zappa：@sxqs-yang认领
* Sanic - asyncpg
* boto3 - TensorFlow
* gym
* Bokeh
* Blaze
* arrow
* hug至结束

**Comment by sxqs-yang** [comment]
开头 - Zappa：@sxqs-yang认领

**Comment by zilongcc** [comment]
boto3 - TensorFlow：@zilongcc认领

**Comment by zilongcc** [comment]
这个在微信群里说，都已经翻译过了！我们就不必重复翻译吧！

**Comment by ictar** [comment]
已被人捷足先登，我们就不翻译了
