### ISSUE TITLE
是否考虑翻译官方中文文档

### ISSUE THREAD

**Issue by wangqr** [PyCN/PTR#21]
目前官网上的文档已经有英、法、日语，没有中文，而网上能够搜到的文档大多较旧（http://usyiyi.cn/ 上为3.5.2）。是否可以考虑组织中文文档的翻译工作？

PEP-545上对于新开坑语言的说明：
https://www.python.org/dev/peps/pep-0545/#new-translation-procedure

**Comment by HELLKING66666** [comment]
不好意思，近期工作繁忙，抽不出手翻译

在 2017年10月16日 下午1:04，wangqr <notifications@github.com>写道：
